<?php
/**
 * Title: Styled Breadcrumbs Navigation
 * Slug: designsetgo/navigation/breadcrumbs-styled
 * Categories: dsgo-navigation
 * Description: Modern breadcrumbs navigation with icons and hover effects
 * Keywords: breadcrumbs, navigation, trail, hierarchy, wayfinding
 */

defined( 'ABSPATH' ) || exit;

return array(
	'title'      => __( 'Styled Breadcrumbs Navigation', 'designsetgo' ),
	'categories' => array( 'dsgo-navigation' ),
	'viewportWidth' => 1200,
	'content'    => '<!-- wp:designsetgo/section {"style":{"spacing":{"padding":{"top":"var:preset|spacing|30","bottom":"var:preset|spacing|30","left":"var:preset|spacing|30","right":"var:preset|spacing|30"}}},"backgroundColor":"base-2","metadata":{"categories":["dsgo-navigation"],"patternName":"designsetgo/navigation/breadcrumbs-styled","name":"Styled Breadcrumbs Navigation"}} -->
<div class="wp-block-designsetgo-section alignfull dsgo-stack has-base-2-background-color has-background" style="padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--30)"><div class="dsgo-stack__inner" style="max-width:var(--wp--style--global--content-size, 1140px);margin-left:auto;margin-right:auto"><!-- wp:designsetgo/breadcrumbs {"separator":"","separatorIcon":"chevron-right","showHome":true,"homeLabel":"Home","homeIcon":true,"showCurrent":true,"linkCurrent":false,"textColor":"#64748b","separatorColor":"#94a3b8","currentColor":"#0f172a","fontSize":"small"} -->
<nav class="wp-block-designsetgo-breadcrumbs dsgo-breadcrumbs" aria-label="Breadcrumb" style="--dsgo-breadcrumbs-text-color:#64748b;--dsgo-breadcrumbs-separator-color:#94a3b8;--dsgo-breadcrumbs-current-color:#0f172a;font-size:var(--wp--preset--font-size--small)" data-show-home="true" data-home-icon="true" data-show-current="true" data-link-current="false"><ol class="dsgo-breadcrumbs__list"><li class="dsgo-breadcrumbs__item"><a href="#" class="dsgo-breadcrumbs__link dsgo-breadcrumbs__link--home"><span class="dsgo-breadcrumbs__home-icon dsgo-lazy-icon" data-icon-name="home" data-icon-size="16"></span></a></li><li class="dsgo-breadcrumbs__separator" aria-hidden="true"><span class="dsgo-lazy-icon" data-icon-name="chevron-right" data-icon-size="14"></span></li><li class="dsgo-breadcrumbs__item"><a href="#" class="dsgo-breadcrumbs__link">Products</a></li><li class="dsgo-breadcrumbs__separator" aria-hidden="true"><span class="dsgo-lazy-icon" data-icon-name="chevron-right" data-icon-size="14"></span></li><li class="dsgo-breadcrumbs__item"><a href="#" class="dsgo-breadcrumbs__link">Category</a></li><li class="dsgo-breadcrumbs__separator" aria-hidden="true"><span class="dsgo-lazy-icon" data-icon-name="chevron-right" data-icon-size="14"></span></li><li class="dsgo-breadcrumbs__item dsgo-breadcrumbs__item--current" aria-current="page">Current Page</li></ol></nav>
<!-- /wp:designsetgo/breadcrumbs --></div></div>
<!-- /wp:designsetgo/section -->

<!-- wp:designsetgo/section {"style":{"spacing":{"padding":{"top":"var:preset|spacing|30","bottom":"var:preset|spacing|30"}}},"backgroundColor":"contrast","metadata":{"categories":["dsgo-navigation"],"patternName":"designsetgo/navigation/breadcrumbs-styled","name":"Styled Breadcrumbs Navigation Dark"}} -->
<div class="wp-block-designsetgo-section alignfull dsgo-stack has-contrast-background-color has-background" style="padding-top:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30)"><div class="dsgo-stack__inner" style="max-width:var(--wp--style--global--content-size, 1140px);margin-left:auto;margin-right:auto"><!-- wp:designsetgo/breadcrumbs {"separator":"","separatorIcon":"arrow-right","showHome":true,"homeLabel":"Home","homeIcon":false,"showCurrent":true,"linkCurrent":false,"textColor":"rgba(255,255,255,0.7)","separatorColor":"rgba(255,255,255,0.4)","currentColor":"#ffffff","fontSize":"small"} -->
<nav class="wp-block-designsetgo-breadcrumbs dsgo-breadcrumbs" aria-label="Breadcrumb" style="--dsgo-breadcrumbs-text-color:rgba(255,255,255,0.7);--dsgo-breadcrumbs-separator-color:rgba(255,255,255,0.4);--dsgo-breadcrumbs-current-color:#ffffff;font-size:var(--wp--preset--font-size--small)" data-show-home="true" data-home-icon="false" data-show-current="true" data-link-current="false"><ol class="dsgo-breadcrumbs__list"><li class="dsgo-breadcrumbs__item"><a href="#" class="dsgo-breadcrumbs__link">Home</a></li><li class="dsgo-breadcrumbs__separator" aria-hidden="true"><span class="dsgo-lazy-icon" data-icon-name="arrow-right" data-icon-size="14"></span></li><li class="dsgo-breadcrumbs__item"><a href="#" class="dsgo-breadcrumbs__link">Services</a></li><li class="dsgo-breadcrumbs__separator" aria-hidden="true"><span class="dsgo-lazy-icon" data-icon-name="arrow-right" data-icon-size="14"></span></li><li class="dsgo-breadcrumbs__item dsgo-breadcrumbs__item--current" aria-current="page">Web Development</li></ol></nav>
<!-- /wp:designsetgo/breadcrumbs --></div></div>
<!-- /wp:designsetgo/section -->

<!-- wp:designsetgo/section {"style":{"spacing":{"padding":{"top":"var:preset|spacing|30","bottom":"var:preset|spacing|30"}},"border":{"radius":"12px"}},"backgroundColor":"base","metadata":{"categories":["dsgo-navigation"],"patternName":"designsetgo/navigation/breadcrumbs-styled","name":"Styled Breadcrumbs Navigation Card"}} -->
<div class="wp-block-designsetgo-section alignfull dsgo-stack has-base-background-color has-background" style="border-radius:12px;padding-top:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30)"><div class="dsgo-stack__inner" style="max-width:var(--wp--style--global--content-size, 1140px);margin-left:auto;margin-right:auto"><!-- wp:designsetgo/row {"verticalAlignment":"center","style":{"spacing":{"padding":{"top":"0","bottom":"0","left":"0","right":"0"}}},"layout":{"type":"flex","justifyContent":"space-between","flexWrap":"wrap"}} -->
<div class="wp-block-designsetgo-row alignfull dsgo-flex dsgo-no-width-constraint" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0"><div class="dsgo-flex__inner" style="display:flex;flex-wrap:wrap;gap:var(--wp--style--block-gap,24px);align-items:center;justify-content:space-between"><!-- wp:designsetgo/breadcrumbs {"separator":"/","showHome":true,"homeLabel":"Home","homeIcon":false,"showCurrent":true,"linkCurrent":false,"textColor":"#6366f1","separatorColor":"#cbd5e1","currentColor":"#334155","fontSize":"small"} -->
<nav class="wp-block-designsetgo-breadcrumbs dsgo-breadcrumbs" aria-label="Breadcrumb" style="--dsgo-breadcrumbs-text-color:#6366f1;--dsgo-breadcrumbs-separator-color:#cbd5e1;--dsgo-breadcrumbs-current-color:#334155;font-size:var(--wp--preset--font-size--small)" data-show-home="true" data-home-icon="false" data-show-current="true" data-link-current="false"><ol class="dsgo-breadcrumbs__list"><li class="dsgo-breadcrumbs__item"><a href="#" class="dsgo-breadcrumbs__link">Home</a></li><li class="dsgo-breadcrumbs__separator" aria-hidden="true">/</li><li class="dsgo-breadcrumbs__item"><a href="#" class="dsgo-breadcrumbs__link">Blog</a></li><li class="dsgo-breadcrumbs__separator" aria-hidden="true">/</li><li class="dsgo-breadcrumbs__item"><a href="#" class="dsgo-breadcrumbs__link">Technology</a></li><li class="dsgo-breadcrumbs__separator" aria-hidden="true">/</li><li class="dsgo-breadcrumbs__item dsgo-breadcrumbs__item--current" aria-current="page">Article Title</li></ol></nav>
<!-- /wp:designsetgo/breadcrumbs -->

<!-- wp:designsetgo/icon-button {"text":"Back to Blog","icon":"arrow-left","iconPosition":"start","style":{"border":{"radius":"6px"},"spacing":{"padding":{"top":"8px","bottom":"8px","left":"16px","right":"16px"}}}} -->
<a class="wp-block-designsetgo-icon-button dsgo-icon-button wp-block-button wp-block-button__link wp-element-button" style="border-radius:6px;display:inline-flex;align-items:center;justify-content:center;gap:8px;width:auto;padding-top:8px;padding-right:16px;padding-bottom:8px;padding-left:16px" href="#" target="_self"><span class="dsgo-icon-button__icon dsgo-lazy-icon" style="display:flex;align-items:center;justify-content:center;width:20px;height:20px;flex-shrink:0" data-icon-name="arrow-left" data-icon-size="20"></span><span class="dsgo-icon-button__text">Back to Blog</span></a>
<!-- /wp:designsetgo/icon-button --></div></div>
<!-- /wp:designsetgo/row --></div></div>
<!-- /wp:designsetgo/section -->',
);
