<?php
/**
 * Title: Event Countdown Hero
 * Slug: designsetgo/hero/hero-event-countdown
 * Categories: dsgo-hero
 * Description: Full-screen hero with countdown timer for events and launches
 * Keywords: hero, countdown, event, launch, timer
 */

defined( 'ABSPATH' ) || exit;

return array(
	'title'      => __( 'Event Countdown Hero', 'designsetgo' ),
	'categories' => array( 'dsgo-hero' ),
	'viewportWidth' => 1200,
	'content'    => '<!-- wp:designsetgo/section {"style":{"spacing":{"padding":{"top":"var:preset|spacing|80","bottom":"120px","left":"var:preset|spacing|30","right":"var:preset|spacing|30"}},"color":{"gradient":"linear-gradient(135deg,rgb(30,27,75) 0%,rgb(76,29,149) 100%)"}},"className":"has-dsgo-parallax","metadata":{"categories":["dsgo-hero"],"patternName":"designsetgo/hero/hero-event-countdown","name":"Event Countdown Hero"}} -->
<div class="wp-block-designsetgo-section alignfull dsgo-stack has-dsgo-parallax has-background" style="background:linear-gradient(135deg,rgb(30,27,75) 0%,rgb(76,29,149) 100%);padding-top:var(--wp--preset--spacing--80);padding-right:var(--wp--preset--spacing--30);padding-bottom:120px;padding-left:var(--wp--preset--spacing--30)"><div class="dsgo-stack__inner" style="max-width:var(--wp--style--global--content-size, 1140px);margin-left:auto;margin-right:auto"><!-- wp:designsetgo/section {"constrainWidth":false,"style":{"spacing":{"padding":{"top":"0","bottom":"0","left":"0","right":"0"}}},"className":"has-dsgo-text-reveal"} -->
<div class="wp-block-designsetgo-section alignfull dsgo-stack dsgo-no-width-constraint has-dsgo-text-reveal" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0"><div class="dsgo-stack__inner"><!-- wp:designsetgo/pill {"content":"Coming Soon","backgroundColor":"accent-3","textColor":"#ffffff","style":{"spacing":{"margin":{"bottom":"var:preset|spacing|40"}}}} -->
<div class="wp-block-designsetgo-pill aligncenter dsgo-pill has-ffffff-color has-accent-3-background-color has-text-color has-background has-small-font-size" style="margin-bottom:var(--wp--preset--spacing--40)"><span class="dsgo-pill__content">Coming Soon</span></div>
<!-- /wp:designsetgo/pill -->

<!-- wp:heading {"textAlign":"center","level":1,"style":{"typography":{"fontStyle":"normal","fontWeight":"800","fontSize":"clamp(2.5rem, 6vw, 4.5rem)","lineHeight":"1.1"}},"textColor":"base"} -->
<h1 class="wp-block-heading has-text-align-center has-base-color has-text-color" style="font-size:clamp(2.5rem, 6vw, 4.5rem);font-style:normal;font-weight:800;line-height:1.1">The Future of Web Design</h1>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","style":{"spacing":{"margin":{"top":"var:preset|spacing|30","bottom":"var:preset|spacing|50"}},"typography":{"fontSize":"1.25rem"}},"textColor":"base"} -->
<p class="has-text-align-center has-base-color has-text-color" style="margin-top:var(--wp--preset--spacing--30);margin-bottom:var(--wp--preset--spacing--50);font-size:1.25rem">Join us for the biggest product launch of 2025. Reserve your spot today.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:designsetgo/section -->

<!-- wp:designsetgo/section {"constrainWidth":false,"style":{"spacing":{"padding":{"top":"0","bottom":"0","left":"0","right":"0"},"margin":{"bottom":"var:preset|spacing|50"}}},"className":"has-dsgo-animation dsgo-animation-fadeInUp","dsgoAnimationEnabled":true,"dsgoEntranceAnimation":"fadeInUp","dsgoAnimationDuration":600} -->
<div class="wp-block-designsetgo-section alignfull dsgo-stack dsgo-no-width-constraint has-dsgo-animation dsgo-animation-fadeInUp" style="margin-bottom:var(--wp--preset--spacing--50);padding-top:0;padding-right:0;padding-bottom:0;padding-left:0" data-dsgo-animation-enabled="true" data-dsgo-entrance-animation="fadeInUp" data-dsgo-exit-animation="" data-dsgo-animation-trigger="scroll" data-dsgo-animation-duration="600" data-dsgo-animation-delay="0" data-dsgo-animation-easing="ease-out" data-dsgo-animation-offset="100" data-dsgo-animation-once="true"><div class="dsgo-stack__inner"><!-- wp:designsetgo/countdown-timer {"targetDateTime":"2026-02-12T22:42:00.640Z","numberColor":"#FFFFFF","labelColor":"rgba(255,255,255,0.7)","unitBorder":{"color":"#ffffff","style":"solid","width":"2px"},"align":"center","className":"dsgo-countdown-timer\u002d\u002dlarge aligncenter"} -->
<div class="wp-block-designsetgo-countdown-timer dsgo-countdown-timer dsgo-countdown-timer--boxed dsgo-countdown-timer--large aligncenter" style="gap:1rem" data-target-datetime="2026-02-12T22:42:00.640Z" data-timezone="" data-show-days="true" data-show-hours="true" data-show-minutes="true" data-show-seconds="true" data-completion-action="message" data-completion-message="The countdown has ended!"><div class="dsgo-countdown-timer__units"><div class="dsgo-countdown-timer__unit" data-unit-type="days" style="background-color:transparent;border-color:#ffffff;border-width:2px;border-style:solid;border-radius:12px;padding:1.5rem"><div class="dsgo-countdown-timer__number" style="color:#FFFFFF">00</div><div class="dsgo-countdown-timer__label" style="color:rgba(255,255,255,0.7)">Days</div></div><div class="dsgo-countdown-timer__unit" data-unit-type="hours" style="background-color:transparent;border-color:#ffffff;border-width:2px;border-style:solid;border-radius:12px;padding:1.5rem"><div class="dsgo-countdown-timer__number" style="color:#FFFFFF">00</div><div class="dsgo-countdown-timer__label" style="color:rgba(255,255,255,0.7)">Hours</div></div><div class="dsgo-countdown-timer__unit" data-unit-type="minutes" style="background-color:transparent;border-color:#ffffff;border-width:2px;border-style:solid;border-radius:12px;padding:1.5rem"><div class="dsgo-countdown-timer__number" style="color:#FFFFFF">00</div><div class="dsgo-countdown-timer__label" style="color:rgba(255,255,255,0.7)">Min</div></div><div class="dsgo-countdown-timer__unit" data-unit-type="seconds" style="background-color:transparent;border-color:#ffffff;border-width:2px;border-style:solid;border-radius:12px;padding:1.5rem"><div class="dsgo-countdown-timer__number" style="color:#FFFFFF">00</div><div class="dsgo-countdown-timer__label" style="color:rgba(255,255,255,0.7)">Sec</div></div></div><div class="dsgo-countdown-timer__completion-message" style="display:none">The countdown has ended!</div></div>
<!-- /wp:designsetgo/countdown-timer --></div></div>
<!-- /wp:designsetgo/section -->

<!-- wp:designsetgo/section {"constrainWidth":false,"style":{"spacing":{"padding":{"top":"0","bottom":"0","left":"0","right":"0"}}},"className":"has-dsgo-animation dsgo-animation-fadeInUp","dsgoAnimationEnabled":true,"dsgoEntranceAnimation":"fadeInUp","dsgoAnimationDuration":600} -->
<div class="wp-block-designsetgo-section alignfull dsgo-stack dsgo-no-width-constraint has-dsgo-animation dsgo-animation-fadeInUp" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0" data-dsgo-animation-enabled="true" data-dsgo-entrance-animation="fadeInUp" data-dsgo-exit-animation="" data-dsgo-animation-trigger="scroll" data-dsgo-animation-duration="600" data-dsgo-animation-delay="0" data-dsgo-animation-easing="ease-out" data-dsgo-animation-offset="100" data-dsgo-animation-once="true"><div class="dsgo-stack__inner"><!-- wp:designsetgo/row {"style":{"spacing":{"padding":{"top":"0","bottom":"0","left":"0","right":"0"}}},"layout":{"type":"flex","orientation":"horizontal","justifyContent":"center","flexWrap":"wrap"}} -->
<div class="wp-block-designsetgo-row alignfull dsgo-flex dsgo-no-width-constraint" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0"><div class="dsgo-flex__inner" style="display:flex;justify-content:center;flex-wrap:wrap"><!-- wp:designsetgo/icon-button {"text":"Reserve Your Spot","icon":"calendar","backgroundColor":"base","textColor":"contrast","style":{"border":{"radius":"8px"},"spacing":{"padding":{"top":"var:preset|spacing|30","bottom":"var:preset|spacing|30","left":"var:preset|spacing|50","right":"var:preset|spacing|50"}}}} -->
<button class="wp-block-designsetgo-icon-button dsgo-icon-button wp-block-button wp-block-button__link wp-element-button" style="border-radius:8px;display:inline-flex;align-items:center;justify-content:center;gap:8px;width:auto;flex-direction:row;background-color:var(--wp--preset--color--base);color:var(--wp--preset--color--contrast);padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--50)" type="button"><span class="dsgo-icon-button__icon dsgo-lazy-icon" style="display:flex;align-items:center;justify-content:center;width:20px;height:20px;flex-shrink:0" data-icon-name="calendar" data-icon-size="20"></span><span class="dsgo-icon-button__text">Reserve Your Spot</span></button>
<!-- /wp:designsetgo/icon-button -->

<!-- wp:designsetgo/icon-button {"text":"Learn More","icon":"info","className":"has-text-color","backgroundColor":"accent-6","style":{"border":{"radius":"8px","width":"2px","color":"#ffffff"},"spacing":{"padding":{"top":"var:preset|spacing|30","bottom":"var:preset|spacing|30","left":"var:preset|spacing|50","right":"var:preset|spacing|50"}},"color":{"text":"#ffffff"}}} -->
<button class="wp-block-designsetgo-icon-button dsgo-icon-button wp-block-button wp-block-button__link wp-element-button has-text-color has-border-color" style="border-color:#ffffff;border-width:2px;border-radius:8px;display:inline-flex;align-items:center;justify-content:center;gap:8px;width:auto;flex-direction:row;background-color:var(--wp--preset--color--accent-6);color:#ffffff;padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--50)" type="button"><span class="dsgo-icon-button__icon dsgo-lazy-icon" style="display:flex;align-items:center;justify-content:center;width:20px;height:20px;flex-shrink:0" data-icon-name="info" data-icon-size="20"></span><span class="dsgo-icon-button__text">Learn More</span></button>
<!-- /wp:designsetgo/icon-button --></div></div>
<!-- /wp:designsetgo/row --></div></div>
<!-- /wp:designsetgo/section -->

<!-- wp:designsetgo/section {"constrainWidth":false,"style":{"spacing":{"padding":{"top":"var:preset|spacing|50","bottom":"0","left":"0","right":"0"}}},"className":"has-dsgo-animation dsgo-animation-fadeIn","dsgoAnimationEnabled":true,"dsgoEntranceAnimation":"fadeIn","dsgoAnimationDuration":600} -->
<div class="wp-block-designsetgo-section alignfull dsgo-stack dsgo-no-width-constraint has-dsgo-animation dsgo-animation-fadeIn" style="padding-top:var(--wp--preset--spacing--50);padding-right:0;padding-bottom:0;padding-left:0" data-dsgo-animation-enabled="true" data-dsgo-entrance-animation="fadeIn" data-dsgo-exit-animation="" data-dsgo-animation-trigger="scroll" data-dsgo-animation-duration="600" data-dsgo-animation-delay="0" data-dsgo-animation-easing="ease-out" data-dsgo-animation-offset="100" data-dsgo-animation-once="true"><div class="dsgo-stack__inner"><!-- wp:designsetgo/counter-group {"columns":4,"textColor":"base","style":{"elements":{"link":{"color":{"text":"var:preset|color|base"}}}}} -->
<div class="wp-block-designsetgo-counter-group dsgo-counter-group has-base-color has-text-color has-link-color" style="align-self:stretch;--dsgo-counter-columns-desktop:4;--dsgo-counter-columns-tablet:2;--dsgo-counter-columns-mobile:1;--dsgo-counter-gap:32px" data-animation-duration="2" data-animation-delay="0" data-animation-easing="easeOutQuad" data-use-grouping="true" data-separator="," data-decimal="."><div class="dsgo-counter-group__inner dsgo-counter-group__inner--align-center"><!-- wp:designsetgo/counter {"uniqueId":"counter-v1yewizj8","endValue":25,"suffix":"+","label":"Workshops"} -->
<div class="wp-block-designsetgo-counter dsgo-counter" id="counter-v1yewizj8" style="text-align:center" data-start-value="0" data-end-value="25" data-decimals="0" data-prefix="" data-suffix="+" data-duration="2" data-delay="0" data-easing="easeOutQuad" data-use-grouping="true" data-separator="," data-decimal="."><div class="dsgo-counter__content icon-top"><div class="dsgo-counter__number"><span class="dsgo-counter__value">0</span></div></div><div class="dsgo-counter__label">Workshops</div></div>
<!-- /wp:designsetgo/counter -->

<!-- wp:designsetgo/counter {"uniqueId":"counter-qz34p03f1","endValue":3,"label":"Day Event"} -->
<div class="wp-block-designsetgo-counter dsgo-counter" id="counter-qz34p03f1" style="text-align:center" data-start-value="0" data-end-value="3" data-decimals="0" data-prefix="" data-suffix="" data-duration="2" data-delay="0" data-easing="easeOutQuad" data-use-grouping="true" data-separator="," data-decimal="."><div class="dsgo-counter__content icon-top"><div class="dsgo-counter__number"><span class="dsgo-counter__value">0</span></div></div><div class="dsgo-counter__label">Day Event</div></div>
<!-- /wp:designsetgo/counter -->

<!-- wp:designsetgo/counter {"uniqueId":"counter-1o901ccay","endValue":5000,"label":"Attendees"} -->
<div class="wp-block-designsetgo-counter dsgo-counter" id="counter-1o901ccay" style="text-align:center" data-start-value="0" data-end-value="5000" data-decimals="0" data-prefix="" data-suffix="" data-duration="2" data-delay="0" data-easing="easeOutQuad" data-use-grouping="true" data-separator="," data-decimal="."><div class="dsgo-counter__content icon-top"><div class="dsgo-counter__number"><span class="dsgo-counter__value">0</span></div></div><div class="dsgo-counter__label">Attendees</div></div>
<!-- /wp:designsetgo/counter -->

<!-- wp:designsetgo/counter {"uniqueId":"counter-1o901ccay","endValue":20,"decimals":1,"suffix":"%","label":"Expert Speakers"} -->
<div class="wp-block-designsetgo-counter dsgo-counter" id="counter-1o901ccay" style="text-align:center" data-start-value="0" data-end-value="20" data-decimals="1" data-prefix="" data-suffix="%" data-duration="2" data-delay="0" data-easing="easeOutQuad" data-use-grouping="true" data-separator="," data-decimal="."><div class="dsgo-counter__content icon-top"><div class="dsgo-counter__number"><span class="dsgo-counter__value">0</span></div></div><div class="dsgo-counter__label">Expert Speakers</div></div>
<!-- /wp:designsetgo/counter --></div></div>
<!-- /wp:designsetgo/counter-group --></div></div>
<!-- /wp:designsetgo/section --></div></div>
<!-- /wp:designsetgo/section -->',
);
