/**
 * Tabs Block - Save Component
 *
 * Renders tab navigation and panels on frontend
 */

import { useBlockProps, useInnerBlocksProps } from '@wordpress/block-editor';

export default function Save({ attributes }) {
	const {
		uniqueId,
		orientation,
		activeTab,
		alignment,
		mobileBreakpoint,
		mobileMode,
		enableDeepLinking,
		gap,
		tabStyle,
		tabColor,
		tabBackgroundColor,
		activeTabColor,
		activeTabBackgroundColor,
		tabBorderColor,
	} = attributes;

	const blockProps = useBlockProps.save({
		className: `dsg-tabs dsg-tabs-${uniqueId} dsg-tabs--${orientation} dsg-tabs--${tabStyle} dsg-tabs--align-${alignment}`,
		'data-active-tab': activeTab,
		'data-mobile-breakpoint': mobileBreakpoint,
		'data-mobile-mode': mobileMode,
		'data-deep-linking': enableDeepLinking ? 'true' : 'false',
		style: {
			'--dsg-tabs-gap': gap,
			...(tabColor && { '--dsg-tab-color': tabColor }),
			...(tabBackgroundColor && { '--dsg-tab-bg': tabBackgroundColor }),
			...(activeTabColor && { '--dsg-tab-color-active': activeTabColor }),
			...(activeTabBackgroundColor && {
				'--dsg-tab-bg-active': activeTabBackgroundColor,
			}),
			...(tabBorderColor && { '--dsg-tab-border-color': tabBorderColor }),
		},
	});

	const innerBlocksProps = useInnerBlocksProps.save({
		className: 'dsg-tabs__panels',
	});

	return (
		<div {...blockProps}>
			{/* Tab navigation will be generated by frontend JS from innerBlocks */}
			<div className="dsg-tabs__nav" role="tablist"></div>

			{/* Tab panels */}
			<div {...innerBlocksProps} />
		</div>
	);
}
