<?php
/**
 * LLMS TXT Conflict Detector
 *
 * Detects and reports conflicts with physical llms.txt files.
 *
 * @package DesignSetGo
 * @since 1.4.0
 */

namespace DesignSetGo\LLMS_Txt;

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Conflict_Detector Class
 *
 * Handles detection and reporting of file conflicts.
 */
class Conflict_Detector {
	/**
	 * Check if a physical llms.txt file exists that would conflict.
	 *
	 * When a physical file exists in the site root, the web server serves it
	 * directly before WordPress can handle the request via rewrite rules.
	 *
	 * @return bool True if a conflicting file exists.
	 */
	public function has_conflict(): bool {
		return file_exists( ABSPATH . 'llms.txt' );
	}

	/**
	 * Get information about the conflicting file.
	 *
	 * @return array|null File info or null if no conflict.
	 */
	public function get_info(): ?array {
		$file_path = ABSPATH . 'llms.txt';

		if ( ! file_exists( $file_path ) ) {
			return null;
		}

		return array(
			'path'     => $file_path,
			'size'     => filesize( $file_path ),
			'modified' => filemtime( $file_path ),
			'writable' => is_writable( $file_path ),
		);
	}

	/**
	 * Display admin notice when a file conflict is detected.
	 */
	public function maybe_show_notice(): void {
		if ( ! current_user_can( 'manage_options' ) ) {
			return;
		}

		$settings = \DesignSetGo\Admin\Settings::get_settings();
		if ( empty( $settings['llms_txt']['enable'] ) ) {
			return;
		}

		if ( ! $this->has_conflict() ) {
			return;
		}

		$screen = get_current_screen();
		if ( ! $screen || ! in_array( $screen->id, array( 'dashboard', 'settings_page_designsetgo', 'plugins' ), true ) ) {
			return;
		}

		$conflict_info = $this->get_info();
		?>
		<div class="notice notice-warning">
			<p>
				<strong><?php esc_html_e( 'DesignSetGo: llms.txt File Conflict Detected', 'designsetgo' ); ?></strong>
			</p>
			<p>
				<?php
				printf(
					/* translators: %s: File path */
					esc_html__( 'A physical llms.txt file exists at %s. This file is being served by your web server instead of the dynamic version generated by DesignSetGo.', 'designsetgo' ),
					'<code>' . esc_html( $conflict_info['path'] ) . '</code>'
				);
				?>
			</p>
			<p>
				<?php esc_html_e( 'To use the dynamic llms.txt feature, you need to rename or delete the existing file. It may have been created by your hosting provider or another plugin.', 'designsetgo' ); ?>
			</p>
		</div>
		<?php
	}
}
