<?php
/**
 * Title: Masonry Gallery with Lightbox
 * Slug: designsetgo/gallery/gallery-masonry-modal
 * Categories: dsgo-gallery
 * Description: Masonry-style image gallery with modal lightbox
 * Keywords: gallery, masonry, lightbox, modal, images
 */

defined( 'ABSPATH' ) || exit;

return array(
	'title'      => __( 'Masonry Gallery with Lightbox', 'designsetgo' ),
	'categories' => array( 'dsgo-gallery' ),
	'content'    => '<!-- wp:designsetgo/section {"style":{"spacing":{"padding":{"top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"backgroundColor":"base-2","metadata":{"categories":["dsgo-gallery"],"patternName":"designsetgo/gallery/gallery-masonry-modal","name":"Masonry Gallery with Lightbox"}} -->
<div class="wp-block-designsetgo-section alignfull dsgo-stack has-base-2-background-color has-background" style="padding-top:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70)"><div class="dsgo-stack__inner" style="max-width:var(--wp--style--global--content-size, 1140px);margin-left:auto;margin-right:auto"><!-- wp:designsetgo/section {"dsgoTextReveal":{"enabled":true,"color":"rgba(0,0,0,0.08)","splitMode":"words"},"style":{"spacing":{"margin":{"bottom":"var:preset|spacing|50"},"padding":{"top":"0","bottom":"0","left":"0","right":"0"}}},"className":"has-dsgo-text-reveal"} -->
<div class="wp-block-designsetgo-section alignfull dsgo-stack has-dsgo-text-reveal" style="margin-bottom:var(--wp--preset--spacing--50);padding-top:0;padding-right:0;padding-bottom:0;padding-left:0" data-dsgo-text-reveal-enabled="true" data-dsgo-text-reveal-color="rgba(0,0,0,0.08)" data-dsgo-text-reveal-split-mode="words"><div class="dsgo-stack__inner" style="max-width:var(--wp--style--global--content-size, 1140px);margin-left:auto;margin-right:auto"><!-- wp:heading {"textAlign":"center","fontSize":"x-large"} -->
<h2 class="wp-block-heading has-text-align-center has-x-large-font-size">Our Work</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","fontSize":"medium"} -->
<p class="has-text-align-center has-medium-font-size">Click on any image to view in fullscreen</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:designsetgo/section -->

<!-- wp:designsetgo/grid {"columns":3,"tabletColumns":2,"mobileColumns":1,"style":{"spacing":{"blockGap":"var:preset|spacing|30","padding":{"top":"0","bottom":"0","left":"0","right":"0"}}}} -->
<div class="wp-block-designsetgo-grid alignfull dsgo-grid dsgo-grid-cols-3 dsgo-grid-cols-tablet-2 dsgo-grid-cols-mobile-1 dsgo-no-width-constraint" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0"><div class="dsgo-grid__inner" style="display:grid;grid-template-columns:repeat(3, 1fr);align-items:start;row-gap:var(--wp--preset--spacing--30);column-gap:var(--wp--preset--spacing--30)"><!-- wp:designsetgo/section {"dsgoAnimation":{"type":"fadeIn","duration":"normal","delay":"none","easing":"ease"},"constrainWidth":false,"style":{"spacing":{"padding":{"top":"0","bottom":"0","left":"0","right":"0"}},"border":{"radius":"12px"}},"className":"has-dsgo-animation dsgo-animation-fadeIn"} -->
<div class="wp-block-designsetgo-section alignfull dsgo-stack dsgo-no-width-constraint has-dsgo-animation dsgo-animation-fadeIn" style="border-radius:12px;padding-top:0;padding-right:0;padding-bottom:0;padding-left:0" data-dsgo-animation="fadeIn" data-dsgo-animation-duration="normal" data-dsgo-animation-delay="none" data-dsgo-animation-easing="ease" data-dsgo-animation-once="true"><div class="dsgo-stack__inner"><!-- wp:image {"sizeSlug":"large","style":{"border":{"radius":"12px"}},"className":"dsgo-gallery-item","dsgoModalTrigger":"dsgo-gallery-modal-1"} -->
<figure class="wp-block-image size-large has-custom-border dsgo-gallery-item"><img src="https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&amp;h=400&amp;fit=crop" alt="Abstract art" style="border-radius:12px" data-dsgo-modal-trigger="dsgo-gallery-modal-1"/></figure>
<!-- /wp:image --></div></div>
<!-- /wp:designsetgo/section -->

<!-- wp:designsetgo/section {"dsgoAnimation":{"type":"fadeIn","duration":"normal","delay":"100ms","easing":"ease"},"constrainWidth":false,"style":{"spacing":{"padding":{"top":"0","bottom":"0","left":"0","right":"0"}},"border":{"radius":"12px"}},"className":"has-dsgo-animation dsgo-animation-fadeIn"} -->
<div class="wp-block-designsetgo-section alignfull dsgo-stack dsgo-no-width-constraint has-dsgo-animation dsgo-animation-fadeIn" style="border-radius:12px;padding-top:0;padding-right:0;padding-bottom:0;padding-left:0" data-dsgo-animation="fadeIn" data-dsgo-animation-duration="normal" data-dsgo-animation-delay="100ms" data-dsgo-animation-easing="ease" data-dsgo-animation-once="true"><div class="dsgo-stack__inner"><!-- wp:image {"sizeSlug":"large","style":{"border":{"radius":"12px"}},"className":"dsgo-gallery-item","dsgoModalTrigger":"dsgo-gallery-modal-2"} -->
<figure class="wp-block-image size-large has-custom-border dsgo-gallery-item"><img src="https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=600&amp;h=800&amp;fit=crop" alt="Modern architecture" style="border-radius:12px" data-dsgo-modal-trigger="dsgo-gallery-modal-2"/></figure>
<!-- /wp:image --></div></div>
<!-- /wp:designsetgo/section -->

<!-- wp:designsetgo/section {"dsgoAnimation":{"type":"fadeIn","duration":"normal","delay":"200ms","easing":"ease"},"constrainWidth":false,"style":{"spacing":{"padding":{"top":"0","bottom":"0","left":"0","right":"0"}},"border":{"radius":"12px"}},"className":"has-dsgo-animation dsgo-animation-fadeIn"} -->
<div class="wp-block-designsetgo-section alignfull dsgo-stack dsgo-no-width-constraint has-dsgo-animation dsgo-animation-fadeIn" style="border-radius:12px;padding-top:0;padding-right:0;padding-bottom:0;padding-left:0" data-dsgo-animation="fadeIn" data-dsgo-animation-duration="normal" data-dsgo-animation-delay="200ms" data-dsgo-animation-easing="ease" data-dsgo-animation-once="true"><div class="dsgo-stack__inner"><!-- wp:image {"sizeSlug":"large","style":{"border":{"radius":"12px"}},"className":"dsgo-gallery-item","dsgoModalTrigger":"dsgo-gallery-modal-3"} -->
<figure class="wp-block-image size-large has-custom-border dsgo-gallery-item"><img src="https://images.unsplash.com/photo-1579547621113-e4bb2a19bdd6?w=600&amp;h=500&amp;fit=crop" alt="Product design" style="border-radius:12px" data-dsgo-modal-trigger="dsgo-gallery-modal-3"/></figure>
<!-- /wp:image --></div></div>
<!-- /wp:designsetgo/section -->

<!-- wp:designsetgo/section {"dsgoAnimation":{"type":"fadeIn","duration":"normal","delay":"300ms","easing":"ease"},"constrainWidth":false,"style":{"spacing":{"padding":{"top":"0","bottom":"0","left":"0","right":"0"}},"border":{"radius":"12px"}},"className":"has-dsgo-animation dsgo-animation-fadeIn"} -->
<div class="wp-block-designsetgo-section alignfull dsgo-stack dsgo-no-width-constraint has-dsgo-animation dsgo-animation-fadeIn" style="border-radius:12px;padding-top:0;padding-right:0;padding-bottom:0;padding-left:0" data-dsgo-animation="fadeIn" data-dsgo-animation-duration="normal" data-dsgo-animation-delay="300ms" data-dsgo-animation-easing="ease" data-dsgo-animation-once="true"><div class="dsgo-stack__inner"><!-- wp:image {"sizeSlug":"large","style":{"border":{"radius":"12px"}},"className":"dsgo-gallery-item","dsgoModalTrigger":"dsgo-gallery-modal-4"} -->
<figure class="wp-block-image size-large has-custom-border dsgo-gallery-item"><img src="https://images.unsplash.com/photo-1618556450994-a6a128ef0d9d?w=600&amp;h=700&amp;fit=crop" alt="Creative workspace" style="border-radius:12px" data-dsgo-modal-trigger="dsgo-gallery-modal-4"/></figure>
<!-- /wp:image --></div></div>
<!-- /wp:designsetgo/section -->

<!-- wp:designsetgo/section {"dsgoAnimation":{"type":"fadeIn","duration":"normal","delay":"400ms","easing":"ease"},"constrainWidth":false,"style":{"spacing":{"padding":{"top":"0","bottom":"0","left":"0","right":"0"}},"border":{"radius":"12px"}},"className":"has-dsgo-animation dsgo-animation-fadeIn"} -->
<div class="wp-block-designsetgo-section alignfull dsgo-stack dsgo-no-width-constraint has-dsgo-animation dsgo-animation-fadeIn" style="border-radius:12px;padding-top:0;padding-right:0;padding-bottom:0;padding-left:0" data-dsgo-animation="fadeIn" data-dsgo-animation-duration="normal" data-dsgo-animation-delay="400ms" data-dsgo-animation-easing="ease" data-dsgo-animation-once="true"><div class="dsgo-stack__inner"><!-- wp:image {"sizeSlug":"large","style":{"border":{"radius":"12px"}},"className":"dsgo-gallery-item","dsgoModalTrigger":"dsgo-gallery-modal-5"} -->
<figure class="wp-block-image size-large has-custom-border dsgo-gallery-item"><img src="https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&amp;h=400&amp;fit=crop" alt="Brand identity" style="border-radius:12px" data-dsgo-modal-trigger="dsgo-gallery-modal-5"/></figure>
<!-- /wp:image --></div></div>
<!-- /wp:designsetgo/section -->

<!-- wp:designsetgo/section {"dsgoAnimation":{"type":"fadeIn","duration":"normal","delay":"500ms","easing":"ease"},"constrainWidth":false,"style":{"spacing":{"padding":{"top":"0","bottom":"0","left":"0","right":"0"}},"border":{"radius":"12px"}},"className":"has-dsgo-animation dsgo-animation-fadeIn"} -->
<div class="wp-block-designsetgo-section alignfull dsgo-stack dsgo-no-width-constraint has-dsgo-animation dsgo-animation-fadeIn" style="border-radius:12px;padding-top:0;padding-right:0;padding-bottom:0;padding-left:0" data-dsgo-animation="fadeIn" data-dsgo-animation-duration="normal" data-dsgo-animation-delay="500ms" data-dsgo-animation-easing="ease" data-dsgo-animation-once="true"><div class="dsgo-stack__inner"><!-- wp:image {"sizeSlug":"large","style":{"border":{"radius":"12px"}},"className":"dsgo-gallery-item","dsgoModalTrigger":"dsgo-gallery-modal-6"} -->
<figure class="wp-block-image size-large has-custom-border dsgo-gallery-item"><img src="https://images.unsplash.com/photo-1558655146-d09347e92766?w=600&amp;h=600&amp;fit=crop" alt="Digital illustration" style="border-radius:12px" data-dsgo-modal-trigger="dsgo-gallery-modal-6"/></figure>
<!-- /wp:image --></div></div>
<!-- /wp:designsetgo/section --></div></div>
<!-- /wp:designsetgo/grid -->

<!-- wp:designsetgo/modal {"modalId":"dsgo-gallery-modal-1","animationType":"fade","overlayOpacity":90} -->
<div id="dsgo-gallery-modal-1" role="dialog" aria-modal="true" aria-label="Image lightbox" aria-hidden="true" data-dsgo-modal="true" data-modal-id="dsgo-gallery-modal-1" data-animation-type="fade" data-animation-duration="300" data-close-on-backdrop="true" data-close-on-esc="true" data-disable-body-scroll="true" data-allow-hash-trigger="true" data-update-url-on-open="false" data-auto-trigger-type="none" data-auto-trigger-delay="0" data-auto-trigger-frequency="always" data-cookie-duration="7" data-exit-intent-sensitivity="medium" data-exit-intent-min-time="5" data-exit-intent-exclude-mobile="true" data-scroll-depth="50" data-scroll-direction="down" data-time-on-page="30" data-gallery-group-id="gallery-lightbox" data-gallery-index="0" data-show-gallery-navigation="true" data-navigation-style="arrows" data-navigation-position="sides" class="wp-block-designsetgo-modal dsgo-modal"><div class="dsgo-modal__backdrop" style="background-color:#000000;opacity:0.9" aria-hidden="true"></div><div class="dsgo-modal__dialog"><div class="dsgo-modal__content" style="border-style:none;border-width:0px;width:90vw;max-width:1200px;background:transparent"><!-- wp:image {"sizeSlug":"full"} -->
<figure class="wp-block-image size-full"><img src="https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&amp;h=800&amp;fit=crop" alt="Abstract art"/></figure>
<!-- /wp:image --><button class="dsgo-modal__close dsgo-modal__close--inside-top-right" style="width:32px;height:32px;color:#ffffff" type="button" aria-label="Close modal"><svg width="100%" height="100%" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path d="M18 6L6 18M6 6L18 18" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path></svg></button></div></div></div>
<!-- /wp:designsetgo/modal -->

<!-- wp:designsetgo/modal {"modalId":"dsgo-gallery-modal-2","animationType":"fade","overlayOpacity":90} -->
<div id="dsgo-gallery-modal-2" role="dialog" aria-modal="true" aria-label="Image lightbox" aria-hidden="true" data-dsgo-modal="true" data-modal-id="dsgo-gallery-modal-2" data-animation-type="fade" data-animation-duration="300" data-close-on-backdrop="true" data-close-on-esc="true" data-disable-body-scroll="true" data-allow-hash-trigger="true" data-update-url-on-open="false" data-auto-trigger-type="none" data-auto-trigger-delay="0" data-auto-trigger-frequency="always" data-cookie-duration="7" data-exit-intent-sensitivity="medium" data-exit-intent-min-time="5" data-exit-intent-exclude-mobile="true" data-scroll-depth="50" data-scroll-direction="down" data-time-on-page="30" data-gallery-group-id="gallery-lightbox" data-gallery-index="1" data-show-gallery-navigation="true" data-navigation-style="arrows" data-navigation-position="sides" class="wp-block-designsetgo-modal dsgo-modal"><div class="dsgo-modal__backdrop" style="background-color:#000000;opacity:0.9" aria-hidden="true"></div><div class="dsgo-modal__dialog"><div class="dsgo-modal__content" style="border-style:none;border-width:0px;width:90vw;max-width:1200px;background:transparent"><!-- wp:image {"sizeSlug":"full"} -->
<figure class="wp-block-image size-full"><img src="https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=1200&amp;h=1600&amp;fit=crop" alt="Modern architecture"/></figure>
<!-- /wp:image --><button class="dsgo-modal__close dsgo-modal__close--inside-top-right" style="width:32px;height:32px;color:#ffffff" type="button" aria-label="Close modal"><svg width="100%" height="100%" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path d="M18 6L6 18M6 6L18 18" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path></svg></button></div></div></div>
<!-- /wp:designsetgo/modal -->

<!-- wp:designsetgo/modal {"modalId":"dsgo-gallery-modal-3","animationType":"fade","overlayOpacity":90} -->
<div id="dsgo-gallery-modal-3" role="dialog" aria-modal="true" aria-label="Image lightbox" aria-hidden="true" data-dsgo-modal="true" data-modal-id="dsgo-gallery-modal-3" data-animation-type="fade" data-animation-duration="300" data-close-on-backdrop="true" data-close-on-esc="true" data-disable-body-scroll="true" data-allow-hash-trigger="true" data-update-url-on-open="false" data-auto-trigger-type="none" data-auto-trigger-delay="0" data-auto-trigger-frequency="always" data-cookie-duration="7" data-exit-intent-sensitivity="medium" data-exit-intent-min-time="5" data-exit-intent-exclude-mobile="true" data-scroll-depth="50" data-scroll-direction="down" data-time-on-page="30" data-gallery-group-id="gallery-lightbox" data-gallery-index="2" data-show-gallery-navigation="true" data-navigation-style="arrows" data-navigation-position="sides" class="wp-block-designsetgo-modal dsgo-modal"><div class="dsgo-modal__backdrop" style="background-color:#000000;opacity:0.9" aria-hidden="true"></div><div class="dsgo-modal__dialog"><div class="dsgo-modal__content" style="border-style:none;border-width:0px;width:90vw;max-width:1200px;background:transparent"><!-- wp:image {"sizeSlug":"full"} -->
<figure class="wp-block-image size-full"><img src="https://images.unsplash.com/photo-1579547621113-e4bb2a19bdd6?w=1200&amp;h=1000&amp;fit=crop" alt="Product design"/></figure>
<!-- /wp:image --><button class="dsgo-modal__close dsgo-modal__close--inside-top-right" style="width:32px;height:32px;color:#ffffff" type="button" aria-label="Close modal"><svg width="100%" height="100%" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path d="M18 6L6 18M6 6L18 18" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path></svg></button></div></div></div>
<!-- /wp:designsetgo/modal -->

<!-- wp:designsetgo/modal {"modalId":"dsgo-gallery-modal-4","animationType":"fade","overlayOpacity":90} -->
<div id="dsgo-gallery-modal-4" role="dialog" aria-modal="true" aria-label="Image lightbox" aria-hidden="true" data-dsgo-modal="true" data-modal-id="dsgo-gallery-modal-4" data-animation-type="fade" data-animation-duration="300" data-close-on-backdrop="true" data-close-on-esc="true" data-disable-body-scroll="true" data-allow-hash-trigger="true" data-update-url-on-open="false" data-auto-trigger-type="none" data-auto-trigger-delay="0" data-auto-trigger-frequency="always" data-cookie-duration="7" data-exit-intent-sensitivity="medium" data-exit-intent-min-time="5" data-exit-intent-exclude-mobile="true" data-scroll-depth="50" data-scroll-direction="down" data-time-on-page="30" data-gallery-group-id="gallery-lightbox" data-gallery-index="3" data-show-gallery-navigation="true" data-navigation-style="arrows" data-navigation-position="sides" class="wp-block-designsetgo-modal dsgo-modal"><div class="dsgo-modal__backdrop" style="background-color:#000000;opacity:0.9" aria-hidden="true"></div><div class="dsgo-modal__dialog"><div class="dsgo-modal__content" style="border-style:none;border-width:0px;width:90vw;max-width:1200px;background:transparent"><!-- wp:image {"sizeSlug":"full"} -->
<figure class="wp-block-image size-full"><img src="https://images.unsplash.com/photo-1618556450994-a6a128ef0d9d?w=1200&amp;h=1400&amp;fit=crop" alt="Creative workspace"/></figure>
<!-- /wp:image --><button class="dsgo-modal__close dsgo-modal__close--inside-top-right" style="width:32px;height:32px;color:#ffffff" type="button" aria-label="Close modal"><svg width="100%" height="100%" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path d="M18 6L6 18M6 6L18 18" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path></svg></button></div></div></div>
<!-- /wp:designsetgo/modal -->

<!-- wp:designsetgo/modal {"modalId":"dsgo-gallery-modal-5","animationType":"fade","overlayOpacity":90} -->
<div id="dsgo-gallery-modal-5" role="dialog" aria-modal="true" aria-label="Image lightbox" aria-hidden="true" data-dsgo-modal="true" data-modal-id="dsgo-gallery-modal-5" data-animation-type="fade" data-animation-duration="300" data-close-on-backdrop="true" data-close-on-esc="true" data-disable-body-scroll="true" data-allow-hash-trigger="true" data-update-url-on-open="false" data-auto-trigger-type="none" data-auto-trigger-delay="0" data-auto-trigger-frequency="always" data-cookie-duration="7" data-exit-intent-sensitivity="medium" data-exit-intent-min-time="5" data-exit-intent-exclude-mobile="true" data-scroll-depth="50" data-scroll-direction="down" data-time-on-page="30" data-gallery-group-id="gallery-lightbox" data-gallery-index="4" data-show-gallery-navigation="true" data-navigation-style="arrows" data-navigation-position="sides" class="wp-block-designsetgo-modal dsgo-modal"><div class="dsgo-modal__backdrop" style="background-color:#000000;opacity:0.9" aria-hidden="true"></div><div class="dsgo-modal__dialog"><div class="dsgo-modal__content" style="border-style:none;border-width:0px;width:90vw;max-width:1200px;background:transparent"><!-- wp:image {"sizeSlug":"full"} -->
<figure class="wp-block-image size-full"><img src="https://images.unsplash.com/photo-1561070791-2526d30994b5?w=1200&amp;h=800&amp;fit=crop" alt="Brand identity"/></figure>
<!-- /wp:image --><button class="dsgo-modal__close dsgo-modal__close--inside-top-right" style="width:32px;height:32px;color:#ffffff" type="button" aria-label="Close modal"><svg width="100%" height="100%" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path d="M18 6L6 18M6 6L18 18" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path></svg></button></div></div></div>
<!-- /wp:designsetgo/modal -->

<!-- wp:designsetgo/modal {"modalId":"dsgo-gallery-modal-6","animationType":"fade","overlayOpacity":90} -->
<div id="dsgo-gallery-modal-6" role="dialog" aria-modal="true" aria-label="Image lightbox" aria-hidden="true" data-dsgo-modal="true" data-modal-id="dsgo-gallery-modal-6" data-animation-type="fade" data-animation-duration="300" data-close-on-backdrop="true" data-close-on-esc="true" data-disable-body-scroll="true" data-allow-hash-trigger="true" data-update-url-on-open="false" data-auto-trigger-type="none" data-auto-trigger-delay="0" data-auto-trigger-frequency="always" data-cookie-duration="7" data-exit-intent-sensitivity="medium" data-exit-intent-min-time="5" data-exit-intent-exclude-mobile="true" data-scroll-depth="50" data-scroll-direction="down" data-time-on-page="30" data-gallery-group-id="gallery-lightbox" data-gallery-index="5" data-show-gallery-navigation="true" data-navigation-style="arrows" data-navigation-position="sides" class="wp-block-designsetgo-modal dsgo-modal"><div class="dsgo-modal__backdrop" style="background-color:#000000;opacity:0.9" aria-hidden="true"></div><div class="dsgo-modal__dialog"><div class="dsgo-modal__content" style="border-style:none;border-width:0px;width:90vw;max-width:1200px;background:transparent"><!-- wp:image {"sizeSlug":"full"} -->
<figure class="wp-block-image size-full"><img src="https://images.unsplash.com/photo-1558655146-d09347e92766?w=1200&amp;h=1200&amp;fit=crop" alt="Digital illustration"/></figure>
<!-- /wp:image --><button class="dsgo-modal__close dsgo-modal__close--inside-top-right" style="width:32px;height:32px;color:#ffffff" type="button" aria-label="Close modal"><svg width="100%" height="100%" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path d="M18 6L6 18M6 6L18 18" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path></svg></button></div></div></div>
<!-- /wp:designsetgo/modal --></div></div>
<!-- /wp:designsetgo/section -->',
);
