name: Label PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label:
    name: Auto-label PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Label based on files changed
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml

      - name: Label based on size
        uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size: xs'
          xs_max_size: 10
          s_label: 'size: s'
          s_max_size: 100
          m_label: 'size: m'
          m_max_size: 500
          l_label: 'size: l'
          l_max_size: 1000
          xl_label: 'size: xl'
